# Generated by Django 4.2.7 on 2023-11-23 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_product_order_favorite_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='currentInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current', to='app.userinfo'),
        ),
    ]
