# Generated by Django 4.2.7 on 2023-11-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_images_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(default='', upload_to='users'),
        ),
    ]
