# Generated by Django 4.2.7 on 2023-11-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_images_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userInfo_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together={('user', 'userInfo_id')},
        ),
    ]
