# Generated by Django 4.2.7 on 2023-11-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_userinfo_userinfo_id_alter_userinfo_unique_together'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ProductType',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('type', models.CharField(default='other', max_length=100)),
        #     ],
        #     options={
        #         'db_table': 'product_type',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='product_type',
        #     field=models.ForeignKey(default='other', on_delete=django.db.models.deletion.CASCADE, to='app.producttype'),
        #     preserve_default=False,
        # ),
    ]
