# Generated by Django 4.2.7 on 2023-11-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
