# Generated by Django 4.2.7 on 2023-11-30 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
