# Generated by Django 4.2.7 on 2023-12-04 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_cart_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='', max_length=10, verbose_name='收货人姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(default='', max_length=30, verbose_name='收货人手机号'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_place',
            field=models.CharField(default='', max_length=100, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='ToBeShipped', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
