# Generated by Django 4.2.7 on 2023-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
