# Generated by Django 4.2.7 on 2023-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='email')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
