# Generated by Django 4.2.7 on 2023-11-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_producttype_product_product_type'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='producttype',
        #     name='type',
        #     field=models.CharField(max_length=100),
        # ),
    ]
