# Generated by Django 4.2.7 on 2023-11-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_producttype_type'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='product_type',
        # ),
    ]
