# Generated by Django 4.2.7 on 2023-11-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_producttype_fathertype_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinfo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='userInfo_id',
        ),
    ]
